@startuml

!include https://gist.githubusercontent.com/fishey2/c9d9d7c7426d3701959789c10e96fdb0/raw/2afa46ecf5e126ad563693a8dccfa3e7ee46a50c/nhs_stylesheet.iuml

participant "GP2GP Messenger" as gp2gp
participant "Inbound MQ" as mq
participant "MHS Adapter" as mhs
participant "Practise"

' This assumes that you have already changed the ODS in the PDS

' PDS Information is in MIM 4.2.00
' Refer to GP2GP in MIM 3.10.0 for this
autonumber "<b>[300]"
activate gp2gp
    group EHR Request Started

        note over gp2gp
            Sending System
                ASID: 200000001161
                ODS: B86041
        end note

        note over Practise
            Receiving System (EMIS)
                ASID: 200000000205
                ODS: N82668
        end note

        gp2gp -> mhs : EHR Request Started (RCMR_IN010000UK05)

            note left
                 Requires:
                * Receiving ASID
                * Sending ASID
                * NHS Number
                * Sending ODS Code
                * Receiving ODS Code
            end note

            activate mhs

            mhs -> Practise : Wrapped RCMR_IN010000UK05
                activate Practise

       else When Sending and Receiving ASID in message is wrong

            <-[NHS_ERROR]- Practise
                note right
                    Message is lost:

                    Possibly is unable to lookup the
                    endpoint information for the
                    receiving system to send the
                    response back.
                end note
        else When the patient's ODS in PDS has not been changed
            Practise -[NHS_ERROR]-> mhs : Wrapped MCCI_IN010000UK13

            mhs -[NHS_ERROR]-> mq : Negative Acknowledgement (MCCI_IN010000UK13)
                activate mq

            mq -> gp2gp : Consume Message (MCCI_IN010000UK13)
                note left
                    Example Reasons:
                    * (19) Sending check indicates that
                        the Requester is not patient'
                        current healthcare provider.
                end note
        else GP2GP Expected Response

            Practise -> mhs : Wrapped RCMR_IN030000UK06

            mhs -> mq : PDS Update Response (RCMR_IN030000UK06)
                activate mq

            mq -> gp2gp : Consume Message (RCMR_IN030000UK06)
                        note left: The response should contain an EHR Extract


            ' In documentation this message is shown to come before
            ' the previous, in reality we have been receiving this after
            ' the RCMR_IN030000UK06 response. The order is not guaranteed.

            ' The GP2GP Specification says that we should get the MCCI_IN010000UK13 as
            ' an acknowledgement of our request and then receive RCMR_IN030000UK06 as
            ' the fulfillment.
            Practise -> mhs : Wrapped MCCI_IN010000UK13
                deactivate Practise

            mhs -> mq : Acknowledgement (MCCI_IN010000UK13)
                deactivate mhs

            mq -> gp2gp : Consume Message (MCCI_IN010000UK13)



    end
deactivate gp2gp
@enduml